export enum EConfig {
  PORT = 'PORT',

  EMAIL_HOST = 'EMAIL_HOST',
  EMAIL_USER = 'EMAIL_USER',
  EMAIL_PASSWORD = 'EMAIL_PASSWORD',

  JWT_ACCESS_SECRET_KEY = 'JWT_ACCESS_SECRET_KEY',
  JWT_EXPIRE_TIME = 'JWT_EXPIRE_TIME',
  ENCRYPTION_PASSWORD = 'ENCRYPTION_PASSWORD',
}
